# this is the backbone used in yolov8
nc: 54
depth_multiple: 1.00  # scales module repeats
width_multiple: 1.00  # scales convolution channels

backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv8, [64, 3, 1]]
  - [-1, 1, SPDConv, [64]]  # 0-P1/2
  - [-1, 1, SPDConv, [128]]  # 1-P2/4
  - [-1, 3, C2f, [256, True]]
  - [-1, 1, Conv8, [512, 3, 2]]  # 3-P3/8
  - [-1, 3, C2f, [512, True]]
  - [-1, 1, Conv8, [1024, 3, 2]]  # 5-P4/16
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, Conv8, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9