__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/custom2.yml',
]

YOLOBackbone:
  cfg: 'configs/rtdetr/include/custom2_backbone.yml'

train_dataloader:
  batch_size: 8
  num_workers: 4

use_amp: False
epoches: 256


optimizer:
  params:
    - params: 'backbone'
      lr: 0.0001

output_dir: ./output/custom2